version: '2'

services:
  api:
    image: spyglass-server
    build:
      context: ./Spyglass.Server
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__MongoDb=mongodb://mongo.data:27017/?uuidRepresentation=standard
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000:5000"
    links:
      - mongo.data

  web:
    image: spyglass-web
    build:
      context: ./Spyglass.Web
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    links:
      - api

  mongo.data:
    image: mongo
    ports:
      - "27017:27017"
