version: "2"

services:
  spyglass:
    image: spyglass
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5000
    ports:
      - "5002:5000"
    links:
      - mongo
      - sqlserver
    volumes:
      - "./db:/etc/spyglass"

  # mongo:
  #   image: mongo:4.1
  #   ports:
  #     - "27017:27017"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Spyglass@123
    ports:
      - "1433:1433"
# volumes:
#   appdata:
