version: '2'

services:
  server:
    image: spyglass
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__MongoDb=mongodb://mongo.data:27017/?uuidRepresentation=standard
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5000
    ports:
      - "5000:5000"
    links:
      - mongo.data

  mongo.data:
    image: mongo:4.1.3
    ports:
      - "27017:27017"
