version: '2'

services:
  api:
    image: spyglass-server
    build:
      context: ./Spyglass.Server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    links:
      - database

  web:
    image: spyglass-web
    build:
      context: ./Spyglass.Web
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    links:
      - api

  database:
    image: mongo
    ports:
      - "27017:27017"
